
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./angular

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 10
      uses: actions/setup-node@v3
      with:
        node-version: 10
    - run: npm ci
    - run: npm run build --if-present

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/exampolytech2024
        username: ${{ secrets.REGISTERY_USERNAME }}
        password: ${{ secrets.REGISTERY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.gha
        push: true
        tags: rg.fr-par.scw.cloud/exampolytech2024/angular:matteo